Updates test case template
zonemaster/zonemaster pull request #1103
Opened 2022-10-06 14:35 UTC by matsduf

## Purpose

* Improves readability of terms by making a dotted list
* Sorts the terms
* Corrects and adds links

## How to test this PR

Review only.

2022-10-10 05:37 UTC, mvw-afnic requested changes
I see just a small typo.

2022-10-10 05:37 UTC, mvw-afnic commented on docs/internal-documentation/templates/specifications/tests/Template01.md
> +* "in-bailiwick" - The terms are used as defined in [RFC 8499][RFC 8499#page-25],
“The term is used”, maybe?

2022-10-10 11:04 UTC, matsduf commented on docs/internal-documentation/templates/specifications/tests/Template01.md
> +* "in-bailiwick" - The terms are used as defined in [RFC 8499][RFC 8499#page-25],
Yes, fixed.

2022-10-10 11:16 UTC, mvw-afnic commented on docs/internal-documentation/templates/specifications/tests/Template01.md
> +* "in-bailiwick" - The terms is used as defined in [RFC 8499][RFC 8499#page-25],
There’s also “terms”, that needs to be changed to “term”.

2022-10-10 13:00 UTC, mvw-afnic approved these changes
Looks good to me.

2022-10-12 09:49 UTC, tgreenx approved these changes

2022-10-12 10:09 UTC, merged