Update CLI usage documentation
zonemaster/zonemaster pull request #1309
Opened 2024-11-13 13:06 UTC by mattias-p

## Purpose

This PR updates the end user documentation for CLI on how to get brief and full command line documentation.

## Context

This the sister PR of zonemaster/zonemaster-cli#389.

## Changes

* `docs/public/using/cli.md`

## How to test this PR

Run the commands in the update and make sure they match the description.

2024-11-13 13:10 UTC, marc-vanderwal commented on docs/public/using/cli.md
> +This includes an exhaustive list of options and in-depth documentation each one,
```suggestion
This includes an exhaustive list of options and in-depth documentation for each one,
```

2024-11-18 16:35 UTC, matsduf requested changes
Besides the comment it looks fine.

2024-11-18 16:35 UTC, matsduf commented on docs/public/development/cli.md
> +man blib/man1/zonemaster-cli.1p
On FreeBSD:
```
man blib/man1/zonemaster-cli.1
```

Isn't simpler to refer to `perldoc -oman zonemaster.cli`?

2024-11-18 23:02 UTC, matsduf commented
Besides, every directory in the public tree must have a `README.md` and all files in the public tree must be linked from `SUMMARY.md` (except `SUMMARY.md` and `book.toml`).

Maybe we should have a CI for this repository, though the link checking does not seem to be black or white.

2024-11-19 16:40 UTC, matsduf reviewed
It looks good, just one small comment.

2024-11-19 16:40 UTC, matsduf commented on docs/public/using/cli.md
> +important command line options.
The command itself does not have to be repeated.

```suggestion
To get brief descriptions of a selection of the most important command line
options run
```

2024-11-20 09:55 UTC, matsduf approved these changes

2024-11-20 09:56 UTC, merged